name: Node.js Build and Deploy
on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string

jobs:
  yarn-build:
    runs-on: ubuntu-latest
    environment: ${{inputs.env}}
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 21.x
        uses: actions/setup-node@v4
        with:
          node-version: 21.x
          cache: yarn
      - name: Run install
        run: yarn install
      - name: Build production bundle
        run: yarn build
      - name: Build production bundle - vitepress
        run: yarn docs:build
        env:
          VITE_GITHUB_TOKEN: ${{ secrets.VITE_GITHUB_TOKEN }}
          VITE_GITHUB_OWNER: ${{ vars.VITE_GITHUB_OWNER }}
          VITE_GITHUB_REPO: ${{ secrets.VITE_GITHUB_REPO }}
          VITE_GITHUB_PATH: ${{ secrets.VITE_GITHUB_PATH }}
      - name: Upload production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{inputs.env}}
          path: |
            dist
  s3-sync:
    needs: yarn-build
    runs-on: ubuntu-latest
    environment: ${{inputs.env}}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-${{inputs.env}}
          path: dist
      - name: Display structure of downloaded files
        run: ls -R dist
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          SOURCE_DIR: dist
