name: Staging

on:
  push:
    branches: ["develop"]
  repository_dispatch:
    types: [trigger-staging-workflow]

jobs:
  build-and-deploy:
    uses: ./.github/workflows/build-and-deploy.yaml
    with:
      env: staging
    secrets: inherit
